import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import '../globals.css'
import Sidebar from '@/components/Sidebar/Sidebar'
import Header from '@/components/Header'

const inter = Poppins({ weight: ['100', '200', '300', '400', '500', '600', '700', '800'], subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={`${inter.className} flex min-h-screen`}>
                <div className='max-w-xs w-full h-screen border-r flex flex-col'>
                    <Sidebar />
                </div>
                <div className='flex-1 flex flex-col h-screen'>
                    <Header />
                    <main className='flex-1 overflow-auto flex flex-col p-6'>
                        {children}
                    </main>
                </div>
            </body>
        </html>
    )
}
